services:
  rabbitmq:
    image: ${RABBITMQ_DOCKER_IMAGE:-rabbitmq:3-management}
    container_name: ${RABBITMQ_DOCKER_CONTAINER_NAME:-rabbitmq_container}
    ports:
      - "${RABBITMQ_PORT:-5675}:5672"
      - "${RABBITMQ_DASHBOARD_PORT:-15676}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}
    command: rabbitmq-server

  srs:
    image: ${SRS_DOCKER_IMAGE:-ossrs/srs:5}
    container_name: ${SRS_DOCKER_CONTAINER_NAME:-srs_container}
    ports:
      - "${SRS_SERVER_PORT:-1935}:1935"
      - "${SRS_HTTP_SERVER_PORT:-8080}:8080"
      - "1985:1985"
    command: /usr/local/srs/objs/srs -c /usr/local/srs/conf/srs.conf

  postgres:
    image: ${POSTGRES_DOCKER_IMAGE:-postgres:13}
    container_name: ${POSTGRES_DOCKER_CONTAINER_NAME:-postgres_container}
    ports:
      - "${POSTGRES_SERVER_PORT:-5435}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD:-your_postgres_password}
      - POSTGRES_DB=${POSTGRES_DATABASE:-your_postgres_database}
    volumes:
      - ${POSTGRES_DATA_DIR:-./volume/postgres/data}:/var/lib/postgresql/data

  redis:
    image: ${REDIS_DOCKER_IMAGE:-redis:6.2.4}
    container_name: ${REDIS_DOCKER_CONTAINER_NAME:-redis_container}
    ports:
      - "${REDIS_SERVER_PORT:-6399}:6379"
    volumes:
      - ${REDIS_DATA_DIR:-./volume/redis/data}:/data
    command: redis-server

volumes:
  postgres_data:
  redis_data: