# MLflow Configuration
MLFLOW_TRACKING_URI: "http://192.168.1.77:5000"
MLFLOW_BACKEND_STORE: "mlruns"
MLFLOW_SERVER_PORT: 5000
MLFLOW_SERVER_HOST: "192.168.1.77"
# MLFLOW_DOCKER_IMAGE: "ghcr.io/mlflow/mlflow"
# MLFLOW_DOCKER_CONTAINER_NAME: "mlflow_container"

# RabbitMQ Configuration
RABBITMQ_HOST: "192.168.1.77"
RABBITMQ_PORT: 5675
RABBITMQ_DASHBOARD_PORT: 15676
RABBITMQ_USER: "guest"
RABBITMQ_PASSWORD: "guest"
RABBITMQ_VHOST: "/"
# RABBITMQ_SERVER_PATH: "/usr/sbin/rabbitmq-server"
# RABBITMQ_DOCKER_IMAGE: "rabbitmq:3-management"
# RABBITMQ_DOCKER_CONTAINER_NAME: "rabbitmq_container"

# Celery Configuration
CELERY_BROKER_URL: "amqp://guest:guest@192.168.1.77:5672/"
CELERY_RESULT_BACKEND: "redis://localhost:6379/0"

# Django Configuration
DJANGO_SECRET_KEY: "your-secret-key-here"
DEBUG: False
ALLOWED_HOSTS: []

# SRS (Simple RTMP Server) Configuration
SRS_SERVER_HOST: "192.168.1.77"
SRS_SERVER_PORT: 1935
SRS_HTTP_SERVER_PORT: 8080
# SRS_DOCKER_IMAGE: "ossrs/srs:5"
# SRS_DOCKER_CONTAINER_NAME: "srs_container"

# MySQL Configuration
# MySQL Configuration
# MYSQL_SERVER_HOST: "localhost"
# MYSQL_SERVER_PORT: 3306
# MYSQL_ROOT_USER: "root"
# MYSQL_ROOT_PASSWORD: "your_mysql_password"
# MYSQL_DATABASE: "your_database_name"
# MYSQL_DOCKER_IMAGE: "mysql:8.0"
# MYSQL_DOCKER_CONTAINER_NAME: "mysql_container"
# MYSQL_DATA_DIR: "/path/to/mysql/data"


# VisionAI Configuration
VISIONAI_RULE_CONFIG_PATH: "djangoFlex_servers/visionAI_server/type_initial_config/rule.yaml"
VISIONAI_ROLE_CONFIG_PATH: "djangoFlex_servers/visionAI_server/type_initial_config/role.yaml"
VISIONAI_ENTITY_TYPE_CONFIG_PATH: "djangoFlex_servers/visionAI_server/type_initial_config/entity_type.yaml"
VISIONAI_SCENE_TYPE_CONFIG_PATH: "djangoFlex_servers/visionAI_server/type_initial_config/scene_type.yaml"

# Redis Server Configuration
# REDIS_SERVER_HOST: "localhost"
# REDIS_SERVER_PORT: 6399
# REDIS_DOCKER_IMAGE: "redis:6.2.4"
# REDIS_DOCKER_CONTAINER_NAME: "redis_container"
# REDIS_DATA_DIR: "/path/to/redis/data"

# PostgreSQL Configuration
POSTGRES_SERVER_HOST: "192.168.1.77"
POSTGRES_SERVER_PORT: 5435
POSTGRES_ROOT_USER: "postgres"
POSTGRES_ROOT_PASSWORD: "your_postgres_password"
POSTGRES_DATABASE: "your_postgres_database"
# POSTGRES_DOCKER_IMAGE: "postgres:13"
# POSTGRES_DOCKER_CONTAINER_NAME: "postgres_container"
# POSTGRES_DATA_DIR: "/path/to/postgres/data"
